version: '3.7'
services:
  mosh-server:
    build:
      context: .
    volumes:
      - ./var/logs/:/var/logs/
    networks:
      - mosh
    command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
networks:
  mosh: {}
